const char *R_VARS[] = {
"R_ARCH","/x86_64",
"R_BROWSER","/usr/bin/open",
"R_BZIPCMD","/usr/bin/bzip2",
"R_DOC_DIR","/Library/Frameworks/R.framework/Resources/doc",
"R_DVIPSCMD","dvips",
"R_GZIPCMD","/usr/bin/gzip",
"R_HOME","/Library/Frameworks/R.framework/Resources",
"R_INCLUDE_DIR","/Library/Frameworks/R.framework/Resources/include",
"R_LATEXCMD","latex",
"R_LIBS_SITE","",
"R_LIBS_USER","~/Library/R/2.11/library",
"R_MAKEINDEXCMD","makeindex",
"R_PAPERSIZE","a4",
"R_PDFLATEXCMD","pdflatex",
"R_PDFVIEWER","/usr/bin/open",
"R_PLATFORM","x86_64-apple-darwin9.8.0",
"R_PRINTCMD","lpr",
"R_RD4DVI","ae",
"R_RD4PDF","times,hyper",
"R_SHARE_DIR","/Library/Frameworks/R.framework/Resources/share",
"R_TEXI2DVICMD","/usr/bin/texi2dvi",
"R_UNZIPCMD","/usr/bin/unzip",
"R_ZIPCMD","/usr/bin/zip",
NULL };
