
// Do not edit!  This file was autogenerated 
//      by ./bootstrap 
//      on Tue Jan  5 20:59:38 CST 2010
//
// svnrevision and svndate are as reported by svn at that point in time,
// compiledate and compiletime are being filled gcc at compilation

#include <stdlib.h>
 
static const char* svnrevision = "178";
static const char* svndate = "2010-01-05 20:57:41";
static const char* compiletime = __TIME__;
static const char* compiledate = __DATE__;

